### ISSUE TITLE
Error in grep("HIT_INDICES=", gsea.edb):length(gsea.edb) : the parameter length is 0

### ISSUE THREAD

**Issue by mzhoufulai** [PeeperLab/Rtoolbox#3]
I used the Rtoolbox to replot the GSEA result, and the R program stop with an error just like the title，i am not sure whether something was wrong with my input. 

I just try to reproduce the result in your paper. 

Thank you !

**Comment by jestlin15** [comment]
Hi May I ask how this was solved please?
