### ISSUE TITLE
Error in file(file, "rt") : invalid 'description' argument.

### ISSUE THREAD

**Issue by mintang92** [PeeperLab/Rtoolbox#5]
Dear Peeper Lab,

I am trying to reproduce the GSEA file using your replotGSEA code in R. I run the GSEA using the desktop version, and the path directory has both the rnk file and the edb file. But the code cannot be executed. The error message returned:

"Error in file(file, "rt") : invalid 'description' argument."
Traceback:
4. file(file, "rt")
3. read.table(file = file, header = header, sep = sep, quote = quote, dec = dec, fill = fill, comment.char = comment.char, ...)
2. read.delim(file = path.rnk, header = FALSE)
1. replotGSEA(path, gene.set = "GBM")

I appreciate if you could offer some suggestions.

Thank you,
Min

**Comment by PeeperLab2** [comment]
Dear Min,

Thank you for using replotGSEA.
I have tried to reproduce your error and I only get this when I set the wrong path.

Please double check if that is the case for you as well. If not, please send me the exact versions numbers etc. Maybe I can reproduce the error then.

Best Oscar


Example of the code I used:
path = "/Users/gsea_home/output/oct14/200629.Gsea.1571042358754"
replotGSEA(path, gene.set = "HALLMARK_IL2_STAT5_SIGNALING")






On 28 Jun 2020, at 11:00, mintang92 <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear Peeper Lab,

I am trying to reproduce the GSEA file using your replotGSEA code in R. I run the GSEA using the desktop version, and the path directory has both the rnk file and the edb file. But the code cannot be executed. The error message returned:

"Error in file(file, "rt") : invalid 'description' argument."
Traceback:
4. file(file, "rt")
3. read.table(file = file, header = header, sep = sep, quote = quote, dec = dec, fill = fill, comment.char = comment.char, ...)
2. read.delim(file = path.rnk, header = FALSE)

  1.  replotGSEA(path, gene.set = "GBM")

I appreciate if you could offer some suggestions.

Thank you,
Min
