### ISSUE TITLE
heatmap is not centered

### ISSUE THREAD

**Issue by Dorina86** [PeeperLab/Rtoolbox#7]
Hi, I've tried to use replotGSEA using my results. It's a very nice function but I found and issue I couldn't fix. The heatmap is not centered. I mean, in the original Java plot white is in the middle of the color scale, but in the  plot of replotGSEA it is shifted sideways. Do you know why? 

**javaGSEA:**
![JavaGSEA](https://user-images.githubusercontent.com/105920480/169514257-82d7e21a-b873-4b7c-a134-704d38b9a9e8.png)

**replotGSEA**
![replotGSEA](https://user-images.githubusercontent.com/105920480/169514271-c132a0bd-44b1-4a3c-a67b-b691a913e188.png)

**Comment by thomasKuilman** [comment]
Please follow this [link](https://github.com/PeeperLab/Rtoolbox/issues/6) to a solved issue on the same topic
