### ISSUE TITLE
In file(file, "rt") ERROR

### ISSUE THREAD

**Issue by yutito** [PeeperLab/Rtoolbox#8]
Dear Peeper Lab,

I am trying to replot the GSEA result using your package.
However, I got the error message as follows:

I executed this code: 
replotGSEA(path,
                  gene.set = this.set, 
                  class.name = "geneA KO vs WT"
                  # metric.range, 
                  # enrichment.score.range
  )

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'path_to_GSEAresult/edb/XXX.rnk': No such file or directory

Actually, I can see the XXX.rnk and that file is not broken. Why is this happening ?

Here is my environment
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)

Thank you,
Yuta

**Comment by thomasKuilman** [comment]
Hi Yuta,

My guess is that you don’t have the right permissions on the folder and/or the .rnk file. Probably this is solved if you adjust permissions and retry the tool. You can test permissions using the file.access() R function.

Best,

Thomas

**Comment by yutito** [comment]
Hi Thoma,

Thank you for your reply.

Actually, I copied the script and wrote the absolute path to the .rnk file
directly. Finally, I got the result. But, I will check the permission as
you suggested.

Thank you very much for your advice and the great package!

Best,
Yuta.

**Comment by thomasKuilman** [comment]
Hi Yuta,

I am happy to hear that the analysis worked now and that you find our tool useful!

Best,

Thomas
